services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - gn-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.17 # Choose a compatible version
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - gn-network
    volumes:
      - es_data:/usr/share/elasticsearch/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_THEME: keycloak
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HTTP_PORT: 8085 # Internal port
      KC_HOSTNAME: https://vigilant-goggles-7p5wwqrxw9vfx554-8085.app.github.dev # Internal hostname
      QUARKUS_DATASOURCE_JDBC_POOL_SIZE: 20
    depends_on:
      - db
    ports:
      - 8085:8085
    volumes:
      - ./realm-export:/opt/keycloak/data/import/export.json # optional
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - gn-network

  geonetwork:
    image: geonetwork:latest # Choose a version
    container_name: geonetwork
    environment:
      - JAVA_OPTS=-Dgeonetwork.elasticsearch.hosts=elasticsearch:9200
      # OIDC Configuration will be done via GeoNetwork's web interface or config files
    ports:
      - "8080:8080" # Expose for Nginx
    networks:
      - gn-network
    depends_on:
      - elasticsearch
      - keycloak
    volumes:
      - geonetwork_data:/usr/local/geonetwork/data
      - geonetwork_config:/usr/local/geonetwork/config

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs # For HTTPS (self-signed or real)
    depends_on:
      - geonetwork
      - keycloak
    networks:
      - gn-network

networks:
  gn-network:
    driver: bridge

volumes:
  es_data:
  keycloak_data:
  geonetwork_data:
  geonetwork_config:
  db-data: