# GeoNetwork Security Configuration for OIDC (Keycloak)
security:
  oauth2:
    enabled: true
    client:
      clientId: geonetwork
      clientSecret: PnqzBJGlWSID2co9LTpdaChtBQs7U3fm
      accessTokenUri: https://ominous-acorn-jq79964gg7gc55rj-8085.app.github.dev/realms/IDP/protocol/openid-connect/token
      userAuthorizationUri: https://ominous-acorn-jq79964gg7gc55rj-8085.app.github.dev/realms/IDP/protocol/openid-connect/auth
      scope: openid profile email
    resource:
      userInfoUri: https://ominous-acorn-jq79964gg7gc55rj-8085.app.github.dev/realms/IDP/protocol/openid-connect/userinfo
    loginUri: https://ominous-acorn-jq79964gg7gc55rj-8085.app.github.dev/realms/IDP/protocol/openid-connect/auth
    logoutUri: https://ominous-acorn-jq79964gg7gc55rj-8085.app.github.dev/realms/IDP/protocol/openid-connect/logout
