keycloak:
  enabled: true
  force: true
  hideLoginForm: true
  clientId: "geonetwork"
  clientSecret: "Wjf73ttbLrNhj3SiS7Fp9jd2oWx91XLe"
  realm: "master"  # Change if using a custom realm
  authServerUrl: "https://solid-space-garbanzo-ppw99vg69p4374j9-8085.app.github.dev/realms/master/protocol/openid-connect/auth"
  redirectUri: "https://solid-space-garbanzo-ppw99vg69p4374j9-8080.app.github.dev/*"
  roleClaim: "roles"
  groupsClaim: "groups"
  usernameClaim: "preferred_username"
  emailClaim: "email"
